import numpy as np
import pandas as pd
data=pd.read_csv('students.csv')

print(data)
print('no of rows and col:', data.shape)
print('1st 5 rows are:', data.head(5))
print('last 3 rows are:', data.tail(3))
data.info()
print(data.isnull())
print(data.isnull().sum())
data['marks']=data['marks'].fillna(0)
print(data.duplicated())
data=data.drop_duplicates()
print(data)
print('average marks is:',data['marks'].mean())
print('highest marks is:',data['marks'].max())
print('lowest marks is:',data['marks'].min())
print('average study_hours is:',data['study_hours'].mean())
print('average attendance is:',data['attendance'].mean())
print('students with marks>70')
print(data[data['marks']>70])
print('students with marks>85')
print(data[data['marks']>85])